### PR TITLE
Android: fix for Uncaught TypeError: Object #<UI> has no method 'createRefreshControl'

### PR DESCRIPTION
**Pull request by falkolab**

### CODE REVIEW

**Comment by mpociot** [comment]
Other conditionals use the Alloy syntax - `if( OS_IOS )`. Wouldn't it be better to use it here as well?

**Comment by nuno** [comment]
This is what I use:

```
Ti.UI.createTableView();
if(OS_IOS){
	Ti.UI.createRefreshControl();
}
```

**Comment by falkolab** [comment]
Better, but not universal. But you already use OS_IOS. Ok

**Comment by nuno** [comment]
@falkolab hare you still have memory issues like we talk in the other day?

**Comment by falkolab** [comment]
@nuno I test it now with fixed custom build sdk.

**Comment by nuno** [comment]
@falkolab something with want to share your me I believe? :)

**Comment by falkolab** [comment]
Of course I will create issue here.

**Comment by nuno** [comment]
@falkolab  cool, we can union forces, I have some fixes features too.

**Pull request merged**
